### PR TITLE
autobuild-linux: code optimization + add fallbacks

### PR DESCRIPTION
**Pull request by nekomekoraiyuu**
- Added fallbacks for `command` aka. `which` (should probably fix installing on fedora)
- Do not call `echo` command repeatedly unless needed
- Added index detection function 
- Added throw error function (Script should automatically stop in some cases if theres an error)
- use `-ep` flag in `read` instead of only `-p` to allow editing (probably arrow keys)
- Use `case` statement instead of multiple `if` and `elif` statements
- Format script

### CODE REVIEW

**Comment by nekomekoraiyuu** [comment]
TO-DO: Do not attempt to install packages if the required packages are already installed

**Comment by itsHanibee** [comment]
actually that's kinda useful

**Comment by nekomekoraiyuu** [comment]
Don't merge yet ; need to fix \\ add nested case statements

**Comment by nekomekoraiyuu** [comment]
> actually that's kinda useful 

O how?

**Comment by nekomekoraiyuu** [comment]
okay fixed everything i guess
; ready to be reviewed

**Comment by nekomekoraiyuu** [comment]
To do done :3

**Comment by nekomekoraiyuu** [comment]
woah merge conflicts need to resolve beuh

**Comment by nekomekoraiyuu** [comment]
Closing PR as requested (?)

**Pull request closed without merging**
